services:
  - type: static_site
    name: suumadin-frontend
    buildCommand: npm --prefix client install && npm --prefix client run build
    publishPath: dist
    buildFilter:
      paths:
        include:
          - /client/**
          - /package.json
