services:
  - type: static_site
    name: suumadin-frontend
    buildCommand: npm --prefix client install && npm --prefix client run build
    publishPath: dist
    buildFilter:
      paths:
        include:
          - /client/**
          - /package.json
    routes:
      - path: /assets/*
        headers:
          - key: Cache-Control
            value: public, max-age=31536000, immutable
      - path: /
        headers:
          - key: Cache-Control
            value: public, max-age=0, must-revalidate
